#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Aug 31 14:11:31 2017

@author: jaguirre
"""

import numpy as np
import matplotlib.pyplot as plt
from astropy import units as u
from astropy import constants as c
from astropy.cosmology import Planck15 as cosmo
import cosmolopy as cp
#%%